name: Continues Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  NODE_VERSION: 22
  NODE_OPTIONS: --max_old_space_size=4096

permissions:
  contents: write
  packages: write
  pull-requests: write
  actions: write

jobs:
  crowdin:
    name: Synchronize with Crowdin
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1 # Should be 1 to avoid parallel builds
      matrix:
        lc: [ar_SA, bg_BG, ca_ES, cs_CZ, da_DA, de_DE, el_GR, es_ES, eu_ES, fr_FR, gl_ES, hu_HU, it_IT, ja_JP, ko_KR, nl_NL, no_NO, pl_PL, pt_PT, ru_RU, sl_SI, sv_SV, tr_TR, uk_UK, zh_CN, zh_TW]
    steps:
      - uses: actions/checkout@v4
      - name: crowdin-action
        uses: crowdin/github-action@v2.7.0
        with:
          upload_sources: true
          upload_translations: true
          source: deb/openmediavault/usr/share/openmediavault/locale/openmediavault.pot                     # Sources pattern
          translation: deb/openmediavault/usr/share/openmediavault/locale/%locale_with_underscore%/openmediavault.po    # Translations pattern
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: 779152
          CROWDIN_PERSONAL_TOKEN: 3e285e682af7f54b44f728bc371c821dc27d7709e1c89329d0f609c393f2c035c192264da7970a71

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: deb/openmediavault/workbench/package-lock.json
      - name: Install CI
        working-directory: deb/openmediavault/workbench/
        run: npm ci
      - name: Build If Present
        working-directory: deb/openmediavault/workbench/
        run: npm run build --if-present

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p debs
      - name: Install Required
        run: sudo apt install debhelper dh-python fakeroot python3-all python3-stdeb python3-yaml -y
      - name: Build deb
        working-directory: deb/openmediavault/
        run: dpkg-buildpackage -us -uc -d -b
      - name: Move File
        run: mv deb/openmediavault_*.deb debs && mv deb/openmediavault_*.buildinfo debs && mv deb/openmediavault_*.changes debs
      - name: List File
        run: cd debs && ls -la
      - uses: actions/upload-artifact@v4
        with:
          path: 'debs/openmediavault_*.deb'
          name: OpenMediaVault Deb File
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          path: 'debs/openmediavault_*.buildinfo'
          name: OpenMediaVault Buildinfo File
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          path: 'debs/openmediavault_*.changes'
          name: OpenMediaVault Changes File
          if-no-files-found: error
 
  test-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: deb/openmediavault/usr/share/openmediavault/unittests/shell
        run: make install

      - name: Run unit tests
        working-directory: deb/openmediavault/usr/share/openmediavault/unittests/shell
        run: make test
